name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - uses: mr-smithers-excellent/docker-build-push@feature/add-build-args
      name: Build & push Docker image
      with:
        image: 'mrsmithers/dmriprep'
        tag: 'latest'
        registry: 'docker.io'
        buildArgs: 'VERSION=1.0,BUILD_DATE=2020-01-15'
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
